#cloud-config
runcmd:
- curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=${install_k3s_version} K3S_URL=${k3s_url} K3S_CLUSTER_SECRET="${k3s_cluster_secret}" sh -
final_message: "The system is finally up, after $UPTIME seconds"
